# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '所在城市', 'verbose_name_plural': '所在城市'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '授课讲师', 'verbose_name_plural': '授课讲师'},
        ),
    ]
